"""
Analytics Routes
Endpoints for analytics, reports, and data export
"""

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
import sys
import os
import datetime
import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

sys.path.append(os.path.dirname(os.path.dirname(__file__)))

try:
    from auth import auth_service as auth
except ImportError:
    import auth

router = APIRouter(prefix="/analytics", tags=["Analytics"])

# Global state
history_log = []

@router.get("/data")
def get_analytics(current_user: auth.User = Depends(auth.get_current_user)):
    """
    Get analytics data
    Requires authentication
    """
    import database as db
    recent_logs = db.get_recent_logs(limit=50)
    return {
        "recent_logs": recent_logs,
        "total_entries": len(recent_logs)
    }

@router.get("/export/csv")
def export_csv(current_user: auth.User = Depends(auth.require_admin)):
    """
    Export historical data as CSV
    Admin only
    """
    if not history_log:
        # Get from database if history_log is empty
        import database as db
        recent_logs = db.get_recent_logs(limit=100)
        df = pd.DataFrame(recent_logs)
    else:
        df = pd.DataFrame(history_log)

    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"crowd_report_{timestamp}.csv"
    file_path = os.path.join(os.path.dirname(__file__), "..", filename)
    df.to_csv(file_path, index=False)

    return FileResponse(file_path, media_type="text/csv", filename=filename)

@router.get("/export/pdf")
def export_pdf(current_user: auth.User = Depends(auth.require_admin)):
    """
    Export professional PDF report with statistics
    Admin only
    """
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"crowd_report_{timestamp}.pdf"
    file_path = os.path.join(os.path.dirname(__file__), "..", filename)

    # Create PDF
    doc = SimpleDocTemplate(file_path, pagesize=letter)
    elements = []
    styles = getSampleStyleSheet()

    # Title
    title = Paragraph("<b>CrowdCount - Infosys</b><br/>Crowd Analytics Report", styles['Title'])
    elements.append(title)
    elements.append(Spacer(1, 20))

    # Metadata
    meta_text = f"<b>Generated:</b> {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}<br/>"
    meta_text += f"<b>Generated by:</b> {current_user.full_name} ({current_user.role})"
    meta = Paragraph(meta_text, styles['Normal'])
    elements.append(meta)
    elements.append(Spacer(1, 20))

    # Zone summary
    import database as db
    thresholds = db.get_all_thresholds()
    
    zone_data = [["Zone Name", "Threshold", "Alert Enabled"]]
    for zone_name, data in thresholds.items():
        zone_data.append([
            zone_name,
            str(data.get("max_capacity", 30)),
            "Yes" if data.get("alert_enabled", True) else "No"
        ])

    zone_table = Table(zone_data)
    zone_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    elements.append(Paragraph("<b>Zone Configuration</b>", styles['Heading2']))
    elements.append(Spacer(1, 10))
    elements.append(zone_table)
    elements.append(Spacer(1, 20))

    # Historical data
    recent_logs = db.get_recent_logs(limit=10)
    if recent_logs:
        elements.append(Paragraph("<b>Recent Activity (Last 10 Entries)</b>", styles['Heading2']))
        elements.append(Spacer(1, 10))
        
        log_data = [["Timestamp", "Total People"]]
        for log in recent_logs:
            log_data.append([log["timestamp"], str(log["total_people"])])
        
        log_table = Table(log_data)
        log_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        elements.append(log_table)

    doc.build(elements)
    return FileResponse(file_path, media_type="application/pdf", filename=filename)

@router.get("/stats")
def get_statistics(current_user: auth.User = Depends(auth.get_current_user)):
    """
    Get statistical summary
    Requires authentication
    """
    import database as db
    recent_logs = db.get_recent_logs(limit=100)
    
    if not recent_logs:
        return {"message": "No data available"}
    
    total_counts = [log["total_people"] for log in recent_logs]
    
    return {
        "total_entries": len(recent_logs),
        "average_count": sum(total_counts) / len(total_counts) if total_counts else 0,
        "max_count": max(total_counts) if total_counts else 0,
        "min_count": min(total_counts) if total_counts else 0,
        "latest_timestamp": recent_logs[0]["timestamp"] if recent_logs else None
    }
